on: 
  push: 
    branches: 
      - dev 
      - main 
  workflow_dispatch: 

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    env: 
      REPO_NAME: "ENT_GIS_DEV.public.quickstart_repo" 
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }} 
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }} 
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }} 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4 
      - name: Install snowflake-cli 
        uses: Snowflake-Labs/snowflake-cli-action@v1.5 
        with: 
          cli-version: "latest" 
          default-config-file-path: ".snowflake/config.toml" 
      - name: Fetch repository changes 
        run: snow git fetch "${REPO_NAME}" 
      - name: Deploy data pipeline to ${{ github.ref_name }} 
        run: | 
          BRANCH_NAME=${{ github.ref_name }} 
          if [ "${BRANCH_NAME}" == "main" ]; then 
            RETENTION_TIME=1 
          else 
            RETENTION_TIME=0 
          fi 
          snow git execute "@${REPO_NAME}/branches/${BRANCH_NAME}/steps/0[134]_*" -D "environment='${BRANCH_NAME}'" -D "retention_time=${RETENTION_TIME}"
